# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictlog',
            name='prob_men',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='predictlog',
            name='prob_women',
            field=models.FloatField(null=True),
        ),
    ]
