# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0002_auto_20161115_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictlog',
            name='prob_men',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='predictlog',
            name='prob_women',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
