# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0004_auto_20161117_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictlog',
            old_name='highlighted',
            new_name='highlight',
        ),
    ]
