# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictapp', '0006_auto_20161118_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictlog',
            name='api_consumer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='predictlog',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='predictlog',
            name='feedback',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='predictlog',
            name='feedback_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
